### ISSUE TITLE
[REQUEST] Option to switch to a theme's dark or light mode specifically

### ISSUE THREAD

**Issue by firinael** [kenset/obsidian-theme-picker#1]
As title says, having the option to switch specifically to a theme's dark or light mode would be very nice. Also would be very nice to be able to bind changing to a specific theme to a hotkey.

Edit: also not sure if possible, but it'd be very nice if you could add the default theme (or "none") as an option for switching.

**Comment by trey-sedate** [comment]
@firinael Great suggestions -- feel free to take a look at PR #2 and see what you think of the Dark Mode/Light Mode toggle in the status bar.

Adding an option for the default theme should be trivial when I can get to it.

Do you have any more details about your use case for changing to a specific theme with a hotkey? I'm picturing something in Settings that maps a custom hotkey to a user-selected theme -- is that what you had in mind? I'd also appreciate any examples you may have of other plugins that allow users to configure their own hotkeys.

**Comment by firinael** [comment]
> I'm picturing something in Settings that maps a custom hotkey to a user-selected theme -- is that what you had in mind?

Not exactly, just having a `Switch to theme #1` (and other numbers) hotkey (user chooses which is `theme #1` in the plugin's settings) would do the trick perfectly, in my opinion.

I'm not sure if there's any way to allow the user to create their own hotkeys, too.

What would "PR #2" be, by the way?

**Comment by trey-sedate** [comment]
I added a dark mode toggle and the None theme. I'll save the hotkey feature for another time, probably transferring it to another issue. PR #2 references the pull request that added the dark mode toggle feature. You should be able to click on #2 
and have it take you to the code, but here is the full link if that's easier: https://github.com/kenset/obsidian-theme-picker/pull/2

**Comment by firinael** [comment]
loved the dark/light mode button!

also I checked your reply through my email so the link wasn't showing up.
