### ISSUE TITLE
[SUGGESTION] Dark/Light Mode Switch

### ISSUE THREAD

**Issue by CHE-11** [kenset/obsidian-theme-picker#10]
I would love to be able to chose dark or light theme directly from the lower menubar or in the modal as well. Like a change dark/light mode next to the Change Theme. 

This plugin has quickly become one of my favorites. Thanks so much!

**Comment by CHE-11** [comment]
Never mind I updated and it was there. Fantastic!

**Comment by trey-sedate** [comment]
Glad you enjoyed it! Please continue making suggestions!
