### ISSUE TITLE
[Suggestions] CSS Snippets selector

### ISSUE THREAD

**Issue by b1uegh0st** [kenset/obsidian-theme-picker#13]
Hi,

 Firstly, thanks for the great plugin. I think the way you execute it for UX is super great.

 Along the line of not having to:
 - Go into the setting. (specific case: Appearance tab)
 - Pick up the mouse.
 - To quickly change something about appearance.

 I would like to suggest if you can find a way to 1. Index the CSS snippets. 2. Add a command "Snippets picker", then one can search the specific snippet and then Enter to tongle it on or off.

 Example use-case: I use certain CSS snippets for:
 - The line connecting the bullets for outliner-like experience (some themes have it, some don't, so that kinda go hand in hand with theme picker).
 - Snippets to change `max-line-width` - also kinda go with the themes, when I use certain theme I want to change the line-width coz of the fonts.

 I think this is something that obsidian dev will not prioritize as a core functionality but it will be a life-saver for some, like me.

 Thanks,
 NA

**Comment by DryIce1** [comment]
hi @b1uegh0st , perhaps you know already, but there is a Snippets Commands plugin, which probably fulfils your needs... with hotkey helper, I have a few snippets linked to hotkeys, e.g. to hide/display YAML. works a treat!

**Comment by b1uegh0st** [comment]
> hi @b1uegh0st , perhaps you know already, but there is a Snippets Commands plugin, which probably fulfils your needs... with hotkey helper, I have a few snippets linked to hotkeys, e.g. to hide/display YAML. works a treat!

That was new than my suggestions. Thanks for letting me know. Let me try that and close this soon.
