### ISSUE TITLE
最新版ob 1.0.0版本切换不了主题

### ISSUE THREAD

**Issue by BonjourL** [kenset/obsidian-theme-picker#15]
主题选择框为空，有主题

**Comment by gkavboy** [comment]
The modal window with list of themes is empty, but theme is install. Not work after update Obsidian to v.1.0

**Comment by trey-sedate** [comment]
Thanks for the heads up! I will work on this.

**Comment by trey-sedate** [comment]
Please update the plugin and try again and let me know if the issue is resolved.

**Comment by trey-sedate** [comment]
Solved another issue with updating the plugin, can confirm that themes appear now in the modal. Thanks for bringing this to my attention!

**Comment by gkavboy** [comment]
All OK! Confirm, plugin works as well.
