### ISSUE TITLE
Plugin cannot be updated or installed fresh

### ISSUE THREAD

**Issue by OsoRojo** [kenset/obsidian-theme-picker#18]
When attempting to update from 1.04 to 1.07, I received a message that the plugin could not be installed.

Enabling and disabling the plugin still seemed to work, though it didn't display the themes (blank box issue)

I then removed the plugin and attempted to reinstall fresh (after reboot) with the same result.

This is on a recently updated Obsidian 1.0 install on Mac with several other plugins installed, but before I go in to exhaustive disabling and troubleshooting I thought I'd see if anyone else can replicate this.

**Comment by trey-sedate** [comment]
Thanks for checking on this, I'll look into it.

**Comment by trey-sedate** [comment]
Fixed by making sure release aligned with manifest.json
